# yml配置信息强依赖Spring，但是项目中的Util以及部分Config不需要依赖Spring，并且Config中的某些值需要配置文件中读取，
# 因此创建该属性文件，采用Classpath读取
# 严格遵守公钥加密，私钥解密

# SM2支撑平台公钥
ruida.sm2-platform-publicKey=MFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEifIXjAkdIIrTOz9AFQdezUTCjTqY18yLxzDc0HIIm37NaM/bvNZklD1jCK+kdQS9Hlx0LabpVVZdYDtemIow+g==
# SM2支撑平台私钥
ruida.sm2-platform-privateKey=

